name: Publish xpu wheel nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - 'release/**'
    tags:
      - 'v*'


permissions: read-all

concurrency:
  group: ${{ github.workflow }}-all-${{ github.sha }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number || '0' }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha || github.sha }}
  BRANCH: ${{ github.event.pull_request.base.ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  clone:
    name: Clone PaddleFormers
    uses: ./.github/workflows/_clone_linux.yml

  publish-wheel-xpu:
    name: Publish xpu wheel nightly (${{ matrix.xpu.XPU_VERSION }}, python${{ matrix.python_version }})
    needs: clone
    if: github.repository == 'PaddlePaddle/PaddleFormers'
    runs-on:
      group: XPU-build
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10"]
        xpu:
          - {XPU_VERSION: xpu-p800, IMAGE_TAG: ci, bos_XPU: xpu-p800}
    env:
      TASK: PaddleFormers-nightly-${{ matrix.xpu.XPU_VERSION }}
      PIP_CACHE_DIR: /home/.cache/pip
      CACHE_DIR: /home/.cache
      REPO_ARCHIVE_URL: ${{ needs.clone.outputs.repo_archive_url }}
      no_proxy: ".bcebos.com,bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"
    steps:
      - name: Check docker image and run container
        run: |
          docker_image="ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/fastdeploy-xpu:${{ matrix.xpu.IMAGE_TAG }}"
          docker pull $docker_image
          container_name=${TASK}-${{ matrix.python_version }}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker run -d -t --name ${container_name} \
            -v "/home/data/cfs:/home/data/cfs" \
            -v "/home/data/cfs/.cache:/home/.cache" \
            -v ${{ github.workspace }}/../../..:/root \
            -v ${{ github.workspace }}/../../../proxy:/root/proxy \
            -v ${{ github.workspace }}:/workspace \
            -e no_proxy \
            -e CACHE_DIR \
            -e PIP_CACHE_DIR \
            -e PR_ID \
            -e COMMIT_ID \
            -e BRANCH \
            -e REPO_ARCHIVE_URL \
            -e AK=${{ secrets.BOS_AK }} \
            -e SK=${{ secrets.BOS_SK }} \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_REPO_NAME=${{ github.repository }} \
            -w /workspace --network=host $docker_image sleep infinity

      - name: Install PaddleFormers
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          rm -rf * .[^.]*
          source /root/proxy || true
          echo "Downloading PaddleFormers archive: ${REPO_ARCHIVE_URL}"
          wget -q --tries=5 --no-proxy ${REPO_ARCHIVE_URL} --no-check-certificate
          tar -xf PaddleFormers.tar.gz --strip-components=1
          rm PaddleFormers.tar.gz
          git config --global --add safe.directory /workspace
          python -m pip install --upgrade pip
          python -m pip install bce-python-sdk==0.8.74
          python -m pip install setuptools wheel
          python -m pip uninstall -y paddlepaddle-xpu fastdeploy-xpu paddleformers
          python -m pip install --pre paddlepaddle-xpu -i https://www.paddlepaddle.org.cn/packages/nightly/xpu-p800
          '

      - name: Build wheel
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          source /root/proxy || true
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            export PADDLEFORMERS_STABLE_VERSION=1
          fi
          python -m pip wheel . --no-deps --no-build-isolation -w dist/
          ls -l dist/
          '

      - name: Upload wheel
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -xc '
          wget -q --no-proxy https://xly-devops.bj.bcebos.com/home/bos_new.tar.gz --no-check-certificate
          mkdir bos
          tar -xf bos_new.tar.gz -C bos
          cd dist
          git -C /workspace rev-parse HEAD > commitid || echo ${COMMIT_ID} > commitid
          if [[ "${{ github.event_name }}" != "push" ]]; then
            python ../bos/BosClient.py paddleformers-*.whl paddle-whl/nightly/${{ matrix.xpu.bos_XPU }}/paddleformers
            export AK=paddle
            export SK=paddle
            python ../bos/BosClient.py paddleformers-*.whl paddle-github-action/PaddleFormers/${BRANCH}/${COMMIT_ID}/${{ matrix.xpu.bos_XPU }}
            cp paddleformers-*.whl paddleformers-0.0.0-py3-none-any.whl
            python ../bos/BosClient.py paddleformers-0.0.0-py3-none-any.whl paddle-github-action/PaddleFormers/${BRANCH}/latest/${{ matrix.xpu.bos_XPU }}
            python ../bos/BosClient.py commitid paddle-github-action/PaddleFormers/${BRANCH}/latest/${{ matrix.xpu.bos_XPU }}
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            python ../bos/BosClient.py paddleformers-*.whl paddle-whl/stable/${{ matrix.xpu.bos_XPU }}/paddleformers
          else
            python ../bos/BosClient.py paddleformers-*.whl paddle-whl/nightly/${{ matrix.xpu.bos_XPU }}/paddleformers
            export AK=paddle
            export SK=paddle
            python ../bos/BosClient.py paddleformers-*.whl paddle-github-action/PaddleFormers/${BRANCH}/${COMMIT_ID}/${{ matrix.xpu.bos_XPU }}
            cp paddleformers-*.whl paddleformers-0.0.0-py3-none-any.whl
            python ../bos/BosClient.py paddleformers-0.0.0-py3-none-any.whl paddle-github-action/PaddleFormers/${BRANCH}/latest/${{ matrix.xpu.bos_XPU }}
            python ../bos/BosClient.py commitid paddle-github-action/PaddleFormers/${BRANCH}/latest/${{ matrix.xpu.bos_XPU }}
          fi
          curl https://www.paddlepaddle.org.cn/inner/whl/update/path/new || true
          '

      - name: Cleanup
        if: ${{ always() }}
        run: |
          set +e
          docker rm -f ${{ env.container_name }}
